/* Default configuration for the SFID Linkage emulator */
export const DEFAULT_CONFIG = {
  schemaVersion: 1,
  system: {
    hostname: "linkage-router",
    timezone: "UTC",
    ntpServer: "pool.ntp.org",
    logLevel: "info",
    uiLanguage: "en",
    uiTheme: "auto",
    uiSoundVolume: 30,
    uiWallpaper: null,
  },
  security: {
    twoFaEnabled: false,
    ipWhitelist: [],
    autoBackup: false,
    autoBackupInterval: "0 2 * * *",
  },
  interfaces: {
    wan: { name: "eth0", mode: "dhcp", ipAddress: "", netmask: "", gateway: "" },
    lan: { name: "eth1", mode: "static", ipAddress: "192.168.1.1", netmask: "255.255.255.0", gateway: "" },
  },
  dhcp: {
    enabled: true,
    interfaceName: "eth1",
    poolStart: "192.168.1.100",
    poolEnd: "192.168.1.199",
    leaseTime: "24h",
    dnsServers: ["1.1.1.1", "8.8.8.8"],
    gateway: "192.168.1.1",
    domain: "local",
  },
  dns: {
    upstreamServers: ["1.1.1.1", "8.8.8.8"],
    cacheEnabled: true,
    cacheSize: 1000,
  },
  nat: {
    masqueradeEnabled: true,
    portForwardRules: [],
  },
  firewall: {
    wanDefaultPolicy: "deny",
    lanDefaultPolicy: "allow",
    rules: [],
  },
  qos: {
    enabled: true,
    downloadMbps: 100,
    uploadMbps: 100,
  },
  wifi: {
    "2.4g": {
      enabled: true,
      ssid: "Linkage-2G",
      password: "linkagepass",
      channel: 6,
      channelWidth: "20",
      security: "wpa2",
      hiddenSsid: false,
    },
    "5g": {
      enabled: true,
      ssid: "Linkage-5G",
      password: "linkagepass",
      channel: 36,
      channelWidth: "80",
      security: "wpa2",
      hiddenSsid: false,
    },
    guest: {
      enabled: false,
      ssid: "Linkage-Guest",
      password: "",
      isolation: true,
      speedLimitMbps: 10,
      lanAccess: false,
    },
  },
  vpn: {
    profiles: [],
  },
  adblock: {
    enabled: false,
    blocklists: ["https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"],
    allowedDomains: [],
  },
  torrent: {
    enabled: false,
    downloadPath: "/downloads",
    maxDownloadMbps: 50,
    maxUploadMbps: 10,
    maxConnections: 50,
  },
};

export const SAMPLE_LOGS = [
  { level: "info", source: "system", message: "System started successfully", details: { version: "1.0.0" } },
  { level: "info", source: "network", message: "Interface eth0 is up (WAN)", details: { ip: "203.0.113.10" } },
  { level: "info", source: "network", message: "Interface eth1 is up (LAN)", details: { ip: "192.168.1.1" } },
  { level: "info", source: "dhcp", message: "DHCP server started on eth1", details: { pool: "192.168.1.100-199" } },
  { level: "info", source: "dns", message: "DNS resolver configured", details: { upstream: ["1.1.1.1", "8.8.8.8"] } },
  { level: "info", source: "firewall", message: "Firewall rules loaded", details: { ruleCount: 0 } },
  { level: "info", source: "nat", message: "NAT masquerade enabled on eth0", details: {} },
  { level: "warn", source: "firewall", message: "Blocked incoming connection from 45.33.32.156:22", details: { srcIp: "45.33.32.156", port: 22 } },
  { level: "info", source: "dhcp", message: "Lease assigned: 192.168.1.100 → AA:BB:CC:DD:EE:01 (laptop-john)", details: {} },
  { level: "info", source: "wifi", message: "Client connected: iphone-sarah on 2.4GHz", details: { signal: -42 } },
  { level: "error", source: "vpn", message: "VPN connection failed: timeout reaching server", details: { profile: "office-vpn" } },
  { level: "info", source: "system", message: "Configuration saved", details: { user: "admin" } },
];
